### ISSUE TITLE
Source Download not working locally

### ISSUE THREAD

**Issue by mbtamuli** [saadq/latexresu.me#26]
After running 
```bash
npm run build
npm start
```
the local server starts. Even the PDF download works. But downloading the Source shows error.

On chrome dev tools console,
```
Failed to load resource: the server responded with a status of 504 (Gateway Timeout) 
    :3000/api/generate/source
```
On the terminal,
```
_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (/home/mbtamuli/latexresu.me/app/server/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendStream (/home/mbtamuli/latexresu.me/app/server/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:96:20)
    at module.exports.ArchiveOutputStream.entry (/home/mbtamuli/latexresu.me/app/server/node_modules/compress-commons/lib/archivers/archive-output-stream.js:88:10)
    at module.exports.ZipStream.entry (/home/mbtamuli/latexresu.me/app/server/node_modules/zip-stream/index.js:138:49)
    at Zip.append (/home/mbtamuli/latexresu.me/app/server/node_modules/archiver/lib/plugins/zip.js:53:15)
    at Archiver._moduleAppend (/home/mbtamuli/latexresu.me/app/server/node_modules/archiver/lib/core.js:172:16)
    at Archiver._onQueueTask (/home/mbtamuli/latexresu.me/app/server/node_modules/archiver/lib/core.js:370:8)
    at /home/mbtamuli/latexresu.me/app/server/node_modules/async/dist/async.js:4045:9
    at process (/home/mbtamuli/latexresu.me/app/server/node_modules/async/dist/async.js:2316:17)
[nodemon] app crashed - waiting for file changes before starting...
[HPM] Error occurred while trying to proxy request /api/generate/source from localhost:3000 to http://localhost:3001 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by saadq** [comment]
Hey @mbtamuli, thanks for reporting an issue. I have a few questions if you don't mind answering:

1. Which OS are you on?
2. Which browser(s) are you using?
3. Which template(s) are you using?
4. Does <kbd>Download Source</kbd> work when using the actual [latexresu.me](https://latexresu.me) website instead of the local app?

**Comment by saadq** [comment]
Also just out of curiosity, what happens when you run `npm test` in the root directory of the project?

**Comment by mbtamuli** [comment]
Sure. Happy to help solve the issue.

1. I'm using Ubuntu 17.04
2. I'm using Google Chrome 58.0.3029.110
3. I tried using Template 6.
4. Yes, `Download Source` works when using the [latexresu.me](https://latexresu.me/) site.

Output of running `npm test`
```

> latexresu.me@0.1.0 test /home/mbtamuli/latexresu.me
> npm run test:client && npm run test:server


> latexresu.me@0.1.0 test:client /home/mbtamuli/latexresu.me
> cd app/client && npm test


> latexresume-client@0.1.0 test /home/mbtamuli/latexresu.me/app/client
> npm run lint --silent && cross-env NODE_ENV=test ava src/tests/**/*.js --fail-fast --verbose


  ✔ actions › generator › synchronous generator actions
  ✔ reducers › form › it should clear school field
  ✔ reducers › form › it should clear job field
  ✔ reducers › form › it should clear job duty field
  ✔ reducers › form › it should clear project field
  ✔ reducers › form › it should clear skill field
  ✔ reducers › form › it should clear award field
  ✔ reducers › ui › it can set the window dimensions
  ✔ reducers › ui › it can zoom in
  ✔ reducers › ui › it can zoom out
  ✔ reducers › ui › it can start printing a resume
  ✔ reducers › ui › it can finish printing a resume
  ✔ reducers › ui › it can show the modal
  ✔ reducers › ui › it can hide the modal
  ✔ reducers › ui › it can show the side nav
  ✔ reducers › ui › it can hide the side nav
  ✔ reducers › ui › it can add a school
  ✔ reducers › ui › it can remove a school
  ✔ reducers › ui › it can add a job
  ✔ reducers › ui › it can remove a job
  ✔ reducers › ui › it can add a job duty
  ✔ reducers › ui › it can remove a job duty
  ✔ reducers › ui › it can add a skill
  ✔ reducers › ui › it can remove a skill
  ✔ reducers › ui › it can add a project
  ✔ reducers › ui › it can remove a project
  ✔ reducers › ui › it can add an award
  ✔ reducers › ui › it can remove an award
  ✔ reducers › generator › it can select a template
  ✔ reducers › generator › it can request resume generation
  ✔ reducers › generator › it can receive a generated resume
  ✔ reducers › generator › it can fail at generating a resume
  ✔ reducers › generator › it can save the current resume data
  ✔ reducers › generator › it can request to download the resume source
  ✔ reducers › generator › it can succeed or fail at downloading the resume source
  ✔ reducers › generator › it can set the page count for the pdf
  ✔ reducers › generator › it can change the current page displayed of the pdf
  ✔ actions › form › form actions
  ✔ actions › ui › ui actions

  39 tests passed [23:36:49]


> latexresu.me@0.1.0 test:server /home/mbtamuli/latexresu.me
> cd app/server && npm test


> saadq-server-boilerplate@0.1.0 test /home/mbtamuli/latexresu.me/app/server
> npm run lint --silent && ava src/tests/**/*.js --fail-fast --verbose


  ✔ sanitizer › sanitizer should trim excess space from values
  ✔ sanitizer › sanitizer should normalize LaTeX symbols
  ✔ sanitizer › sanitizer should recursively remove empty properties from complex objects
  ✔ templates › it should generate a LaTeX document for each template
Uncaught Exception: src/tests/routes.js
  TypeError: Cannot read property 'pipesCount' of undefined
    module.exports.ZipArchiveOutputStream._smartStream (node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:184:11)
    module.exports.ZipArchiveOutputStream._appendStream (node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:96:20)
    module.exports.ArchiveOutputStream.entry (node_modules/compress-commons/lib/archivers/archive-output-stream.js:88:10)
    module.exports.ZipStream.entry (node_modules/zip-stream/index.js:138:49)
    Zip.append (node_modules/archiver/lib/plugins/zip.js:53:15)
    Archiver._moduleAppend (node_modules/archiver/lib/core.js:172:16)
    Archiver._onQueueTask (node_modules/archiver/lib/core.js:370:8)
    node_modules/async/dist/async.js:4045:9
    process (node_modules/async/dist/async.js:2316:17)
    Immediate._onImmediate (node_modules/async/dist/async.js:66:16)



  ✖ Test results were not received from src/tests/routes.js

  4 tests passed [23:36:52]
  2 uncaught exceptions

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! latexresu.me@0.1.0 test:server: `cd app/server && npm test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the latexresu.me@0.1.0 test:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mbtamuli/.npm/_logs/2017-06-11T18_06_52_731Z-debug.log

```

**Comment by saadq** [comment]
Oh, one other question – What version of `node` are you using?

If you're using Node version 8, I think the issue is coming from [here](https://github.com/archiverjs/node-archiver/issues/236). It seems `node-archiver` (the module I'm using to generate a ZIP) is having some issues in the latest version of Node.

**Comment by mbtamuli** [comment]
```➜  latexresu.me git:(master) node --version
v8.0.0
➜  latexresu.me git:(master) npm --version
5.0.0
```
Yes, I'm using node version 8. Checking with the current LTS version(6.11.0). Will update here once I try.

**Comment by mbtamuli** [comment]
This time,
```
➜  latexresu.me git:(master) node --version
v6.11.0
➜  latexresu.me git:(master) npm --version
3.10.10
```

I still get warnings and errors, albeit different ones.
```
➜  latexresu.me git:(master) npm run build

> latexresu.me@0.1.0 build /home/mbtamuli/latexresu.me
> npm run build:client && npm run build:server


> latexresu.me@0.1.0 build:client /home/mbtamuli/latexresu.me
> cd app/client && npm install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/stylint/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> latexresu.me@0.1.0 build:server /home/mbtamuli/latexresu.me
> cd app/server && npm install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

```
➜  latexresu.me git:(master) npm start

> latexresu.me@0.1.0 start /home/mbtamuli/latexresu.me
> npm run start:client & npm run start:server


> latexresu.me@0.1.0 start:server /home/mbtamuli/latexresu.me
> cd app/server && npm run watch


> latexresu.me@0.1.0 start:client /home/mbtamuli/latexresu.me
> cd app/client && npm start


> saadq-server-boilerplate@0.1.0 watch /home/mbtamuli/latexresu.me/app/server
> nodemon src/index.js


> latexresume-client@0.1.0 start /home/mbtamuli/latexresu.me/app/client
> cross-env NODE_ENV=development webpack-dev-server --config webpack.dev.config.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/index.js`
/home/mbtamuli/latexresu.me/app/server/node_modules/koa-bodyparser/index.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mbtamuli/latexresu.me/app/server/src/index.js:2:20)
[nodemon] app crashed - waiting for file changes before starting...
Project is running at http://localhost:3000/
webpack output is served from /
404s will fallback to /index.html
Hash: 6b59535c86383750d3d8
Version: webpack 2.2.1
Time: 13775ms
                                 Asset       Size  Chunks                    Chunk Names
  1e4d110f3638b250a711ddd289f0d145.png     163 kB          [emitted]
 5dc09aebb04b4b7f2198c97af66a11f9.woff    19.2 kB          [emitted]
  6802965ec59f315947714e6db4d33e79.png     184 kB          [emitted]
  2d39346ca0b8f28f4afa4eba23f774f1.png     153 kB          [emitted]
  de2f0747ab8a7687bcd1fb3d0f41b860.png     166 kB          [emitted]
  cd6a6a198c8f7448e36ec53ee816275d.png     210 kB          [emitted]
ddb465b4d9e5c977219e285858b89460.woff2    14.6 kB          [emitted]
  322975563be986b986315a8d48de3c9b.png     195 kB          [emitted]
  06b11df50c7f770888a5e09d17d3e8c2.png     149 kB          [emitted]
  c0d22c37d62915e1a113bf9a6708f453.png     180 kB          [emitted]
  9bf9b406149ffa2d0f23da246f8f7267.png     156 kB          [emitted]
                             bundle.js    12.4 MB       0  [emitted]  [big]  main
                            index.html  662 bytes          [emitted]
chunk    {0} bundle.js (main) 4.31 MB [entry] [rendered]
 [../node_modules/babel-polyfill/lib/index.js] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
 [../node_modules/react-dom/index.js] ./~/react-dom/index.js 59 bytes {0} [built]
 [../node_modules/react-hot-loader/patch.js] ./~/react-hot-loader/patch.js 41 bytes {0} [built]
 [../node_modules/react/react.js] ./~/react/react.js 56 bytes {0} [built]
 [../node_modules/regenerator-runtime/runtime.js] ./~/regenerator-runtime/runtime.js 24.4 kB {0} [built]
 [../node_modules/strip-ansi/index.js] ./~/strip-ansi/index.js 161 bytes {0} [built]
 [../node_modules/url/url.js] ./~/url/url.js 23.3 kB {0} [built]
 [../node_modules/webpack-dev-server/client/index.js?http:/localhost:3000] (webpack)-dev-server/client?http://localhost:3000 5.28 kB {0} [built]
 [../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [0] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server babel-polyfill react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./index.js 100 bytes {0} [built]
 [../node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.57 kB {0} [built]
 [../node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
 [../node_modules/webpack/hot/only-dev-server.js] (webpack)/hot/only-dev-server.js 2.29 kB {0} [built]
 [./index.js] ./src/index.js 852 bytes {0} [built]
 [./styles/index.styl] ./src/styles/index.styl 1.17 kB {0} [built]
     + 1093 hidden modules
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 542 kB [entry] [rendered]
     [../node_modules/html-webpack-plugin/lib/loader.js!./index.html] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 976 bytes {0} [built]
     [../node_modules/lodash/lodash.js] ./~/lodash/lodash.js 540 kB {0} [built]
     [../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
     [../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Compiled successfully.
[HPM] Error occurred while trying to proxy request /api/generate/resume from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

This time, even PDF was not created. Please let me know which version of node you are using so I can try that.

**Comment by saadq** [comment]
Yeah, the app is going to require a version of Node that is at least **v7.6** because I'm using `async/await` in my code. So you can try anywhere from 7.6 and above. So try for something v7.6 or above. 8.0 obviously has issues, but if you switch to 8.1, I believe that should work as well as mentioned in my edit above.

**Comment by mbtamuli** [comment]
Yes it works with 8.1.0, checked. Thanks. Maybe you could mention this on the README if possible.

**Comment by saadq** [comment]
Yep, I'll update the README soon to tell people to avoid v8.0.0 or anything below 7.6. 

As for the test failure, you might be using an older version of latexresu.me. I pushed a commit several days ago [here](https://github.com/saadq/latexresu.me/commit/8fcdb9b268ce6d3e813867003e7b7604ba7fb594) that fixed the test. Try running `git pull` and see if the test passes now.
